export const CREATE_PRODUCT_ITEM = "CREATE_PRODUCT_ITEM";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
// export const ADD_COMMENT = 'ADD_COMMENT'
